name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 7 * * *'  # Every day at 07:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: esphome/build-action@v7
        with:
          yaml-file: test_empty_components.yaml
